# Generated by Django 3.1.4 on 2020-12-09 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201209_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['offering_no']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['sin']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_no']},
        ),
    ]
