# Generated by Django 3.1.4 on 2020-12-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201206_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='start_date',
        ),
    ]
