# Generated by Django 3.1.4 on 2020-12-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201206_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='grade',
            field=models.CharField(max_length=2),
        ),
    ]
