# Generated by Django 3.1.4 on 2020-12-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201206_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
