# Generated by Django 3.1.4 on 2020-12-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='api.course'),
        ),
    ]
